---
name: Analysis - Codacy Security Scan

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - devel
      - develop

jobs:
  codacy:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
